CREATE TABLE [dbo].[User]
(
	[Id]                                 INT                     IDENTITY (1, 1) NOT NULL,
    [Uid]                                UNIQUEIDENTIFIER        NOT NULL,
    [CreatedOn]                          DATETIME                NOT NULL,
    [DeletedOn]                          DATETIME                NULL,  
    [Embg]                               NVARCHAR (255)          NOT NULL           UNIQUE,
    [FirstName]                          NVARCHAR (255)          NOT NULL,
    [LastName]                           NVARCHAR (255)          NOT NULL           UNIQUE,
    [Email]                              NVARCHAR (255)          NOT NULL,
    [PasswordHash]                       NVARCHAR (255)          NOT NULL,
    [PhoneNumber]                        NVARCHAR (255)          NOT NULL           UNIQUE,
    [DateOfEmployment]                   DATETIME                NULL,    
    [DriversCertificateSerialNumber]     NVARCHAR (255)          NULL,
    [DriversCertificateIssueDate]        DATETIME                NULL,
    [DriversCertificateExpiryDate]       DATETIME                NULL,    
    [DrivingLicenseSerialNumber]         NVARCHAR (255)          NULL,
    [DrivingLicenseIssueDate]            DATETIME                NULL,
    [DrivingLicenseExpiryDate]           DATETIME                NULL,    
    [PassportSerialNumber]               NVARCHAR (255)          NULL,
    [PassportIssueDate]                  DATETIME                NULL,
    [PassportExpiryDate]                 DATETIME                NULL,    
    [IdentityCardSerialNumber]           NVARCHAR (255)          NULL,
    [IdentityCardIssueDate]              DATETIME                NULL,
    [IdentityCardExpiryDate]             DATETIME                NULL,
    [CompanyId]                          INT                     NOT NULL,
    [TruckId]                            INT                     NULL,
    [TrailerId]                          INT                     NULL
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Company_User] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([Id]),
    CONSTRAINT [FK_Truck_User] FOREIGN KEY ([TruckId]) REFERENCES [dbo].[Truck] ([Id]),
    CONSTRAINT [FK_Trailer_User] FOREIGN KEY ([TrailerId]) REFERENCES [dbo].[Trailer] ([Id]),
)